### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [Alexscaleb/Tareas-Curso-BioinfInvRepro#1]
¿Genómicos de cloroplasto = cloroplasto completo?

**Comment by Alexscaleb** [comment]
ya modifique la redacción, se trata de 4 transcriptomas que serán mapeados a un genoma de referencia de cloroplasto ya existente.

**Comment by AliciaMstt** [comment]
Ok. Lo que no me queda claro es por qué te clavas e cloroplasto si tienes tanta más información en el transcriptoma.

**Comment by Alexscaleb** [comment]
Hola Alicia, perdón por la respuesta tardía lo que pasa es que estábamos en campo.
Nos interesan los cloroplastos porque los plastos en vainilla pueden transformarse en cloroplastos o feniloplastos. Estos últimos se almacena vainillina, Pero como ya existe un genoma de referencia de los cloroplastos, podemos encontrar algún marcador que diferencie entre estos quimiotipos que ademas se encuentran en 2 condiciones diferentes.
